version: '3'
services:
  gateway:
    build: ssh-gateway
    network_mode: host
    depends_on:
      - "emq"
  forward:
    build: ssh-forward
    network_mode: host
  emq:
    image: emqx/emqx:v3.1.1
    network_mode: host
    environment:
     - EMQ_NAME=emq
     - EMQ_HOST=127.0.0.1
